In [1]:
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn.objects as so

sns.set_theme(style="whitegrid")
so.Plot.config.display["format"] = "svg"
pd.options.mode.chained_assignment = None

In [2]:
# Import the data
data = pd.read_csv('results.csv')
data['ellipsis'] = data['ellipsis'] == 1
data.head(10)

,word,ud_test_head,ud_test_deprel,ud_preds_head,ud_preds_deprel,str_test_head,str_test_deprel,str_preds_head,str_preds_deprel,ellipsis
0,другой,6,amod,6,amod,6,опред,6,опред,False
1,необычный,6,amod,6,amod,6,опред,6,опред,False
2,для,4,case,4,case,2,1-компл,2,1-компл,False
3,системы,2,obl,2,obl,3,предл,3,предл,False
4,образования,4,nmod,4,nmod,4,1-компл,4,квазиагент,False
5,проект,12,nsubj,12,nsubj,12,предик,12,предик,False
6,"""",8,punct,8,punct,8,punct,8,punct,False
7,город,6,appos,6,appos,6,ном-аппоз,6,ном-аппоз,False
8,как,10,mark,10,mark,8,сравнит,8,сравнит,False
9,школа,8,acl,8,acl,9,сравн-союзн,9,сравн-союзн,False

In [10]:
heads = data[['word', 'ud_test_head', 'ud_preds_head', 'str_test_head', 'str_preds_head', 'ellipsis']]
heads = heads[(heads['ud_test_head'] != heads['ud_preds_head']) | (heads['str_test_head'] != heads['str_preds_head'])]

deprels = data[['word', 'ud_test_deprel', 'ud_preds_deprel', 'str_test_deprel', 'str_preds_deprel', 'ellipsis']]
deprels = deprels[(deprels['ud_test_deprel'] != deprels['ud_preds_deprel']) | (deprels['str_test_deprel'] != deprels['str_preds_deprel'])]
deprels.head(10)

,word,ud_test_deprel,ud_preds_deprel,str_test_deprel,str_preds_deprel,ellipsis
4,образования,nmod,nmod,1-компл,квазиагент,False
18,где,advmod,advmod,1-компл,обст,False
24,образования,nmod,nmod,1-компл,квазиагент,False
35,год,obl,obl,3-компл,длительн,False
62,уже,advmod,obl,огранич,огранич,False
75,один,amod,nummod,опред,опред,False
119,быть,conj,cop,сочин,сочин,False
120,с,case,case,обст,присвяз,False
121,системой,obl,conj,предл,предл,False
124,питания,nmod,nmod,атриб,квазиагент,False