In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
from IPython.display import display
from src.utils import build_data_from_suffix

In [2]:
DATA = build_data_from_suffix("morph", csv_dir="csvs")

In [8]:
from src.error_matrix import build_error_matrix

matrix_new = build_error_matrix(DATA, tag="upos", sort_by="total")
matrix_new.to_csv("upos_error_matrix.csv")
matrix_new.head(10)

,,split,full,full_pct,old,old_pct,new,new_pct,total
upos_g_str,upos_g_ud,upos_p_ud,,,,,,,
S,PROPN,NOUN,55,1.07,39,0.97,23,2.09,117
V,AUX,VERB,56,4.27,32,3.57,9,2.16,97
A,PROPN,ADJ,34,28.81,23,19.49,<NA>,NaN,57
S,DET,PRON,30,2.42,13,1.48,2,0.56,45
NUM,ADJ,NUM,17,2.58,13,2.15,0,0.00,30

In [6]:
from src.error_matrix import build_duplets_matrix

matrix_duplets = build_duplets_matrix(DATA, tag="upos", sort_by="total")
matrix_duplets.to_csv("upos_duplets_matrix.csv")
matrix_duplets.head(10)

split          full  full_pct  old  old_pct  new  new_pct  total
upos_g upos_p
PRON   DET       73      1.00   57     1.27   14     0.50    144
PROPN  NOUN      64      1.20   47     1.11   23     2.08    134
PART   ADV      110      2.21    5     0.15    5     0.31    120
DET    PRON      67      1.21   37     0.94   11     0.70    115
AUX    VERB      56      3.68   32     3.05    9     1.90     97
ADV    PART      84      1.04   10     0.17    2     0.09     96
DET    NUM       35      0.63   25     0.63   18     1.15     78
SCONJ  ADV       42      1.40   23     1.12   10     1.07     75
PART   PRON      34      0.68   18     0.53   18     1.13     70
NUM    ADJ       46      1.98   10     0.51    1     0.27     57

In [22]:
from src.utils import save_str_ud_morph_mismatches

out = save_str_ud_morph_mismatches(DATA, "new", "upos", "V", "AUX", "VERB")

### S: PROPN NOUN
Ошибка конвертации

Модель и конвертер как будто бы постоянно путают, много аббревиатур и слов с большой буквы то получают PROPN в разметке, то не получают

15_2003Bez_epokhi: Ленинизм

### PART: PART <-> ADV
Ошибка рассогласования

Разве что тот единственный случай в новом корпусе правда размечен неправильно

### V: AUX VERB