In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
from IPython.display import display
from src.utils import build_data_from_suffix
from src.feats import *

In [2]:
DATA = build_data_from_suffix("morph", csv_dir="csvs")

In [3]:
out, split_results = build_result_table(DATA, filter=True)

In [4]:
out.set_index("sig").sort_values("n_new", ascending=False).head(10)

,n_full,pct_full,n_old,pct_old,n_new,pct_new,total
sig,,,,,,,
"((Animacy, ОД, Anim, Inan),)",64,0.8,26,0.4,47,2.4,137
"((UPOS, S, PROPN, NOUN),)",45,0.9,37,0.9,20,1.8,102
"((UPOS, V, AUX, VERB),)",55,4.2,32,3.6,9,2.2,96
"((Voice, СТРАД, Pass, Mid),)",23,1.1,26,1.5,8,1.8,57
"((UPOS, S, PART, PRON),)",11,12.6,7,12.1,4,13.8,22
"((Tense, НЕПРОШ, Fut, Pres),)",55,7.5,8,1.5,4,1.8,67
"((UPOS, ADV, NUM, ADV),)",23,29.5,4,9.5,3,8.3,30
"((UPOS, S, DET, PRON),)",30,2.4,13,1.5,2,0.6,45
"((UPOS, PART, ADV, PART),)",68,13.7,0,0.0,1,25.0,69
"((UPOS, NUM, NUM, ADJ),)",45,2.0,8,0.4,1,0.3,54

In [6]:
from src.utils import save_sig_cases

tab = out.sort_values("n_new", ascending=False).reset_index(drop=True)

sig = tab.iloc[3]["sig"]
subset = save_sig_cases(split_results["new"]["tokens"], sig)

In [3]:
out_noisy, split_results_noisy = build_result_table(DATA, filter=True, mode="control")

In [4]:
out_noisy.set_index("sig").sort_values("n_new", ascending=False)

,n_full,pct_full,n_old,pct_old,n_new,pct_new,total
sig,,,,,,,
"((Animacy, ОД, Anim, Inan),)",126,1.5,72,1.2,67,3.5,265
"((Gender, СРЕД, Neut, Masc),)",138,1.0,105,1.0,39,1.1,282
"((UPOS, A, DET, NUM),)",33,0.8,23,0.7,17,1.4,73
"((Voice, СТРАД, Pass, Mid),)",68,3.1,48,2.8,17,3.8,133
"((Aspect, СОВ, Perf, ∅), (Tense, ПРОШ, Past, ∅), (UPOS, V, VERB, ADJ), (VerbForm, ПРИЧ, Part, ∅), (Voice, СТРАД, Pass, ∅))",46,3.0,32,2.7,13,3.7,91
"((UPOS, NUM, NUM, DET),)",18,0.8,6,0.3,6,1.8,30
"((Animacy, НЕОД, Inan, ∅), (Case, ИМ, Nom, ∅), (Gender, СРЕД, Neut, ∅), (Number, ЕД, Sing, ∅), (UPOS, S, PRON, SCONJ))",11,1.2,6,1.0,5,1.6,22
"((Gender, СРЕД, Neut, ∅), (Number, ЕД, Sing, ∅), (UPOS, A, ADJ, ADV), (Variant, КР, Short, ∅))",11,1.9,9,2.2,4,2.3,24
"((Animacy, ОД, Anim, ∅), (Case, ВИН, Acc, Gen))",19,2.1,14,2.1,3,1.3,36

In [11]:
from src.utils import save_sig_cases

tab = out_noisy.sort_values("n_new", ascending=False).reset_index(drop=True)

sig = tab.iloc[8]["sig"]
subset = save_sig_cases(split_results_noisy["new"]["tokens"], sig)