In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
from IPython.display import display
from src.utils import build_data_from_suffix

# Markup alignment

In [2]:
from src.align_markup import align_markup

pairs = {
    "full": ("str",     "ud"),
    "old":  ("str-old", "ud-old"),
    "new":  ("str-new", "ud-new"),
}

# align_markup(pairs)

In [3]:
DATA = build_data_from_suffix("syntax", csv_dir="aligned")

# Error matrix

In [4]:
from src.error_matrix import build_error_matrix

matrix_new = build_error_matrix(DATA, "new")
head_new = 5
matrix_new.head(head_new).to_csv("matrix_new.csv")
matrix_new.head(head_new)

,,split,full,full_pct,old,old_pct,new,new_pct,total
deprel_g_str,deprel_g_ud,deprel_p_ud,,,,,,,
предик,nsubj:pass,nsubj,99,8.77,78,8.39,30,15.08,207
опред,acl,amod,48,4.52,29,3.63,17,6.44,94
аппоз,appos,flat:name,36,3.18,15,1.55,15,9.09,66
разъяснит,appos,parataxis,17,77.27,0,0.00,14,66.67,31
атриб,nmod,obl,71,2.49,56,2.46,11,1.90,138

In [5]:
matrix_old = (
    matrix_new.iloc[head_new:]
    .sort_values(by="old", ascending=False)
)
head_old = 7
matrix_old.head(head_old).to_csv("matrix_old.csv")
matrix_old.head(head_old)

,,split,full,full_pct,old,old_pct,new,new_pct,total
deprel_g_str,deprel_g_ud,deprel_p_ud,,,,,,,
1-компл,obl,obj,109,3.31,55,2.07,4,0.62,168
обст,obl,nmod,58,1.18,40,1.02,7,0.68,105
примыкат,appos,parataxis,44,80.00,37,71.15,0,0.00,81
1-компл,obj,obl,149,2.88,30,0.82,6,0.40,185
сравнит,obl,advcl,17,7.46,21,12.65,0,0.00,38
аппоз,appos,nmod,18,1.59,12,1.24,4,2.42,34
root,cop,root,18,36.00,11,52.38,1,3.45,30

In [6]:
matrix_full = (
    matrix_old.iloc[head_old:]
    .sort_values(by="full", ascending=False)
)
head_full = 20
matrix_full.head(head_full).to_csv("matrix_full.csv")
matrix_full.head(head_full)

,,split,full,full_pct,old,old_pct,new,new_pct,total
deprel_g_str,deprel_g_ud,deprel_p_ud,,,,,,,
количест,nummod:gov,nummod,77,24.52,7,4.07,2,1.41,86
сравн-союзн,case,mark,61,93.85,3,60.00,0,0.00,64
присвяз,xcomp,obl,54,76.06,5,50.00,0,0.00,59
1-компл,xcomp,obl,48,3.53,6,0.62,0,0.00,54
обст,obl:tmod,obl,45,80.36,4,100.00,1,1.92,50
2-компл,iobj,obl,43,6.42,6,1.39,0,0.00,49
1-компл,iobj,obl,41,8.44,4,1.26,0,0.00,45
агент,obl:agent,obl,31,81.58,1,100.00,0,0.00,32
аппоз,flat:name,appos,29,4.90,8,1.74,6,4.51,43
2-компл,xcomp,obl,27,18.00,2,2.15,0,0.00,29
вводн,vocative,parataxis,25,73.53,4,100.00,5,16.67,34
огранич,mark,cc,22,81.48,0,0.00,1,4.35,23
сравнит,case,mark,20,100.00,<NA>,NaN,1,5.00,21
огранич,fixed,advmod,20,13.33,4,4.44,6,10.00,30
сравнит,advcl,obl,20,21.51,4,5.00,0,0.00,24
1-компл,acl,obl,20,21.74,1,2.17,0,0.00,21
обст,iobj,obl,19,61.29,<NA>,NaN,1,3.23,20
огранич,cc,advmod,18,23.08,1,1.82,0,0.00,19
атриб,obl,nmod,17,20.73,8,11.59,2,15.38,27
1-компл,det,nmod,16,34.04,1,6.67,0,0.00,17